# Generated by Django 4.0.1 on 2022-03-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='productImage/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=1024)),
                ('image_URL', models.URLField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('files', models.ManyToManyField(to='products.ProductImage')),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_with_category', to='products.category')),
                ('listedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_with_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
