# Generated by Django 4.0.1 on 2022-03-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_files_product_images_remove_product_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='roduct_id',
            new_name='product_id',
        ),
    ]
