# Generated by Django 4.0.1 on 2022-03-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_roduct_id_prices_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
