# Generated by Django 4.0.1 on 2022-04-11 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_watchlist_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Wishlist',
        ),
    ]
