# Generated by Django 4.0.1 on 2022-04-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_seller_alter_product_sellers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
