# Generated by Django 4.0.1 on 2022-04-17 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0005_alter_user_first_name_alter_user_last_name'),
        ('products', '0013_product_defaultseller_product_seller_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(through='products.Product_Seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product_seller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
