# Generated by Django 4.0.1 on 2022-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
